### ISSUE TITLE
Issue with non-standard search queries

### ISSUE THREAD

**Issue by AlexBachmann** [joomla-framework/twitter-api#4]
Hey, I found a strange issue in the Twitter API. Somehow the API fails, when it is searching form non-standard (or better: non alphanumeric) search queries.

// Works fine
$resp = $twitter->search->search('twitter');

// Does not work
$resp = $twitter->search->search('twitter OR joomla');
$resp = $twitter->search->search('from:twitter');
$resp = $twitter->search->search('Christmas 2014');

I could not figure out, what the problem is. But I have a guess: Urlencoding seems to play a role, since the versions which do not work will be encoded (I tried switching between urlencode and rawurlencode but neighter option worked). Another possiblity could be, that the method which produces the Oauth signature fails, when URLs with URL encoded parameters are beeing used. I don't know nearly enough about this signature creating process to figure it out on my own. So I was wondering if anyone of you cold take a look at it and veryfy the issue (and maybe solve it :)

**Comment by mbabker** [comment]
We've deprecated this package, and considering it hasn't been well maintained at this point it's probably heavily out-of-date with the Twitter API and borderline unusable.
